Statistic
nromanen/Ch-095.backend pull request #23
Opened 2019-12-16 15:09 UTC by Qwe1999

2019-12-16 15:35 UTC, clevercattv reviewed
pull request to master...

2019-12-16 21:25 UTC, clevercattv requested changes

2019-12-16 21:25 UTC, clevercattv commented on src/main/java/com/softserve/academy/event/entity/SurveyAnswer.java
> +
import org.hibernate.annotations.NamedQuery; - ?

2019-12-16 21:25 UTC, clevercattv commented on src/main/java/com/softserve/academy/event/dto/QuestionStatisticDTO.java
> +}
Use lombok : 
@Getter
@Setter

2019-12-16 21:25 UTC, clevercattv commented on src/main/resources/database.properties
> +hibernate.connection.password=admin
seriously?

2019-12-16 21:25 UTC, clevercattv commented on src/main/java/com/softserve/academy/event/dto/QuestionStatisticDTO.java
> +    }
For mapping SurveyQuestion to QuestionStatisticDTO you can create interface mapper.
See : service.mapper.QuestionMapper for example.

2019-12-17 11:37 UTC, Qwe1999 commented on src/main/java/com/softserve/academy/event/entity/SurveyAnswer.java
> +
fixed

2019-12-17 11:39 UTC, closed without merging