Check opportunity
nromanen/Ch-095.backend pull request #30
Opened 2019-12-17 16:34 UTC by ViktorPelepiak

2019-12-17 19:34 UTC, volodymyr-chornyi approved these changes

2019-12-17 20:44 UTC, clevercattv requested changes

2019-12-17 20:44 UTC, clevercattv commented on src/main/java/com/softserve/academy/event/controller/FacebookController.java
> +    //        return "profile";
comment

2019-12-17 21:18 UTC, clevercattv approved these changes

2019-12-18 08:51 UTC, vikfil approved these changes

2019-12-18 09:44 UTC, merged